### ISSUE TITLE
Threading/sleep wrongfully appears to take a large chunk of the time

### ISSUE THREAD

**Issue by noamzilo** [benfred/py-spy#156]
When profiling threaded programs, some functions take over 100% of the time. This is due to more than a single thread running.
Is there a way to view real data on multi threaded systems?
Functions calling `input()` or `sleep()` seem to take up the most time, even though the relevant threads are really idle.

![Untitled](https://user-images.githubusercontent.com/4740186/63262027-98213080-c28d-11e9-80cd-2d8bc4215dac.png)

**Comment by benfred** [comment]
The stable release has some issues with detecting thread activity - and one of the notable problems is in functions like sleep/input.

There has been a bunch of work on fixing this though: https://github.com/benfred/py-spy/issues/92 . This involves matching the python thread id with the OS thread id, and then querying the OS to see if the thread is busy or not.

You can try this out with the latest dev release ```pip install py-spy==0.2.0.dev4```

**Comment by noamzilo** [comment]
Do you have an idea about when this will be out in the stable release?

**Comment by benfred** [comment]
I'm working on it - but can't commit to a date more specific than just 'hopefully pretty soon'.

**Comment by benfred** [comment]
fixed in v0.2.0

**Comment by synapticarbors** [comment]
I just wanted to note that using py-spy v0.3.3, I'm still seeing calls to `time.sleep` (cross referencing the reported line numbers from py-spy with the source code), dominate the sampling, using both the `record` and `top` commands. Going line-by-line, it's something like 60% of the time recorded can be mapped to `time.sleep` lines.

**Comment by ineeee** [comment]
hi I can confirm that py-spy v0.3.14 still counts `time.sleep` as actual time. i'm seeing >60% attributed to sleep calls, which make the sampling worthless
